FROM openjdk:8
ADD target/spring-boot-microservices-eureka-server-example-0.0.1-SNAPSHOT.jar  spring-boot-microservices-eureka-server-example-0.0.1-SNAPSHOT.jar
EXPOSE 8761
ENTRYPOINT ["java", "-jar", "spring-boot-microservices-eureka-server-example-0.0.1-SNAPSHOT.jar"]