FROM openjdk:8
ADD target/spring-boot-microservices-example-0.0.1-SNAPSHOT.jar  spring-boot-microservices-example-0.0.1-SNAPSHOT.jar
EXPOSE 3000
ENTRYPOINT ["java", "-jar", "spring-boot-microservices-example-0.0.1-SNAPSHOT.jar"]